# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShowMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShowMe
pod 'AlamofireImage'
pod 'Alamofire'
pod 'IQKeyboardManagerSwift'
pod 'ReachabilitySwift'
pod 'ObjectMapper'

  target 'ShowMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShowMeUITests' do
    # Pods for testing
  end

end
